{% set name = "udsoncan" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/udsoncan-{{ version }}.tar.gz
  sha256: 63f86ac0a6bb08724a0c59cc566ec5ab88e97881526d162e5aa02853bc544142

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - udsoncan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pylessard/python-udsoncan
  summary: Implementation of the Unified Diagnostic Service (UDS) protocol (ISO-14229) used in the automotive industry.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jdmarques
