{% set name = "udsoncan" %}
{% set version = "1.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/udsoncan-{{ version }}.tar.gz
  sha256: 8dfeff52df9a87985de53ddfa649931bf44456d314828b50352c75335207f3d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - udsoncan
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pylessard/python-udsoncan
  summary: Implementation of the Unified Diagnostic Service (UDS) protocol (ISO-14229) used in the automotive industry.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jdmarques
